server:
  port: 8761 #修改端口号
eureka:
  instance:
    hostname: eureka-server #eureka服务端起个名字
  client:
    #在默认情况下，服务注册中心也会把自己当做是一个服务，将自己注册进服务注册中心，所以我们可以通过配置来禁用他的客户端注册行为
    #由于自己就是服务器，不需要注册到自己
    register-With-eureka: false
    #由于自己就是服务器，不需要注册到自己
    fetch-registry: false
    #服务中心 取消自我保护机制,剔除已关停的客户端节点(服务)
    serviceUrl:
      #注册中心的地址
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    #服务中心 取消自我保护机制,剔除已关停的客户端节点(服务) false,剔除
    enable-self-preservation: false
